### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [bitops/simple-stats#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by karan** [comment]
My bad!

**Comment by bitops** [comment]
@karan no worries!

**Comment by bitops** [comment]
@karan I don't mind switching the license to MIT. If you want to send me a PR for that I'll merge it.

**Comment by karan** [comment]
I like beer.. ;)
